helmCharts:
  - repo: https://grafana.github.io/helm-charts
    name: alloy
    version: "1.5.1"
    includeCRDs: true
    namespace: alloy
    releaseName: alloy-ds
    valuesFile: ../../base/alloy/values-ds.yaml

  - repo: https://grafana.github.io/helm-charts
    name: alloy
    version: "1.5.1"
    includeCRDs: true
    namespace: alloy
    releaseName: alloy-misc
    valuesFile: ../../base/alloy/values-misc.yaml

configMapGenerator:
  - name: cluster-env
    namespace: alloy
    literals:
      - CLUSTER_NAME=dev
