helmCharts:
  - repo: https://kyverno.github.io/kyverno
    name: kyverno
    version: "3.6.0"
    includeCRDs: true
    namespace: kyverno
    releaseName: kyverno
    valuesFile: ../../base/kyverno/values.yaml

resources:
  - ../../base/kyverno/replace-docker-hub.yaml
