helmCharts:
  - repo: https://aws.github.io/eks-charts
    name: aws-load-balancer-controller
    version: "1.15.0"
    includeCRDs: true
    namespace: aws-load-balancer-controller
    releaseName: aws-load-balancer-controller
    valuesFile: values.yaml
